services:
  api:
    build: .
    container_name: countries_info_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: ./.env
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: countries_info_db
    restart: unless-stopped
    env_file: ./.env.pg
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
